### ISSUE TITLE
Function to log broken songs

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#10]
## Story or task
As an *MC user* I want to mark the currently playing song as *buggy*.

## Tasks
- [ ] Mark song as playing in the Queue
- [ ] Recognize that the song has some kind of issue
- [ ] Hit the 🐛 button in the “now playing” area of the MC UI. (must be logged in.)
- [ ] Get a dialog that prompts for a very brief, free form hint of the problem with the song.
- [ ] Log the song metadata (artist, title, performing person name field) and the description entered by the MC into a separate `.csv` log file.

## Notes
It's known that this cannot precisely identify the *exact* file that was playing in the music software. But with the metadata this should give enough context for the MC to find the problematic file that need checking or fixing.

**Comment by anlumo** [comment]
Suggested icon `bug_report`.

**Comment by MacLemon** [comment]
Jup, helpful!
