### ISSUE TITLE
Show some Playback history in the queue view

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#11]
## Story or task
As a performing user/MC I want to be able to look up the last few songs that have been performed.

## Tasks
- [ ] check the queue view
- [ ] At the top there's the “now playing” field
- [ ] scroll up beyond the top to get to the history of the songs performed in the past.

## Notes
-

**Comment by MacLemon** [comment]
Works perfectly fine, shows 2 songs before the one currently playing.
