### ISSUE TITLE
Suggest person joins other performers for the same song that's already in the queue.

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#15]
## Story or task
As an MC I want the queue to nudge users…
When they submit a song request for something that's already queued up:
- Encourage the person to communicate with the other performers if it would be OK to join and perform the song together! (informal, get people to talk to each other)
- UI should not prevent them from still submitting the song request (then it's up to the MC how to deal with that.)

## Tasks
- [ ] User searches for song
- [ ] picks song that is already queued up, but not yet playing
- [ ] UI should suggest the person joins the other performers instead of performing the same song multiple times in a single setting (usually bores the audience)
- [ ] UI could show a note with the suggestions, the names that were submitted by the other people who submitted the song earlier

## Notes
Goal is to prevent multiple people from singing the same song over and over in the same night. This is NOT the cantina band after all!

Known issue with that is, that the software won't be able to pinpoint all duplicates, since there are many songs with variants or cover versions. This is then left as an exercise to the MC.

**Comment by MacLemon** [comment]
Hint is shown just fine and also highlighted, excellent.

We'll see if we need a checkbox for people to confirm they *actually* want to double a song. :-)
