### ISSUE TITLE
Welcoming UI when no match is found for search terms, function to wish for a song

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#16]
## Story or task
As a user I want to find *all* the songs that I like to perform, but sadly, not every song in the world exists (yet).

## Tasks
- [ ] User searches for song
- [ ] nothing matches their criteria
- [ ] instead of the search results list show that nothing was found (no need to apologize for that)
- [ ] user *really* wants to tell the MC that their collection is missing an immensely important song!
- [ ] provide a button for song requests that cannot be fulfilled
- [ ] require fields:
  - [ ] title
  - [ ] artist
- [ ] optionally: name of the person who seeks that song
- [ ] Label for the action button to be determined. (Submit can be confused with the normal song submission. It's a request of sorts, but that wording is already used elsewhere. It's certainly not a function for ordering songs, as we cannot make any guarantees the song exists or can be created.)

## Notes
- Everyone can easily come up with a handful of songs that are not in any song library.
- Wording must make clear that this song will certainly not be added tonight!
- having a UI for unfulfillable song requests makes the MC happy, because they don't have to write down stuff on paper during the show
- Maybe it makes sense to show random suggestions in that case below the “nothing found” info? This may cause a lot of new UI challenges though.

**Comment by MacLemon** [comment]
Does what I wanted it to.
